# Generated by Django 5.0.6 on 2024-06-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_skill_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='mana_point',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
