# Generated by Django 5.0.6 on 2024-06-06 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_skill_mana_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player_detail',
            name='rank',
        ),
        migrations.AddField(
            model_name='player_detail',
            name='player_rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.player_rank'),
        ),
    ]
