# Generated by Django 5.0.6 on 2024-06-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_player_detail_rank_player_detail_player_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_detail',
            name='hp',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
