# Generated by Django 5.0.6 on 2024-06-08 12:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_player_detail_hp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player_detail',
            name='skill',
        ),
        migrations.AddField(
            model_name='skill',
            name='skill',
            field=models.ManyToManyField(blank=True, null=True, related_name='player_skill', to=settings.AUTH_USER_MODEL),
        ),
    ]
